---
  - name: Playing with Dictionaries
    gather_facts: no
    hosts: ios
    tasks:
      - name: Gather IOS Facts
        vars:
          credentials:
            username: "{{ username }}"
            password: "{{ password }}"
            host: "{{ ansible_host }}"
        ios_facts:
          provider: "{{ credentials }}"
        register: ios_facts_output
      - name: print interfaces
        debug:
          msg: "{{ ansible_net_interfaces }}"
      - name: Print Dict Item, interfaces and their MTU
        debug:
          msg: "{{ item.key }} , {{ item.value.ipv4[0][address]}}"
        when:
          - "'Loopback' in item.key"
        with_dict: "{{ ansible_net_interfaces }}"
