---
  - name: Playing with Dictionaries
    gather_facts: no
    hosts: ios
    tasks:
      - name: Gather IOS Facts
        vars:
          credentials:
            username: "{{ username }}"
            password: "{{ password }}"
            host: "{{ ansible_host }}"
        ios_facts:
          provider: "{{ credentials }}"
        register: ios_facts_output
      - name: Print Dict Item, interfaces and their MTU
        debug:
          msg: "{{ item.key }} , {{ item.value.mtu}}"
          when:
            - "'Loopback1' in ansible_net_interface"
        with_dict: "{{ ansible_net_interfaces }}"
