---
  - name: Practicing IOS Show Commands
    gather_facts: no
    hosts: csr
    vars:
      credentials:
          host: "{{ ansible_host }}"
          username: "{{ username }}"
          password: "{{ password }}"
    tasks:
      - name: Gimme the routes!
        ios_commands:
          provider: "{{ credentials }}"
          commands: show ip route
        register: output0
      - name: Print Output
        debug:
          msg: "{{ output0 }}"
