---
  - name: Gather Conditional IOS Facts
    gather_facts: no
    hosts: ios
    tasks:
      - name: Gather IOS Facts
        vars:
          credentials:
              username: "{{ username }}"
              password: "{{ password }}"
              host: "{{ ansible_host }}"
        ios_facts:
          provider: "{{ credentials }}"
        register: ios_facts_output
      - name: Print IOS Facts
        debug:
          msg: "{{ ios_facts_output }}"
      - name: Print IOS Serial Number and Version
        debug:
          msg: "SN: {{ ansible_net_serialnum }}, Version: {{ ansible_net_version }}"
      - name: Only Print Hostname When Serial Number Matches
        debug:
          msg: "Hostname: {{ ansible_net_hostname }}, Version: {{ ansible_net_version }}"
        when:
          "'2048005' == ansible_net_serialnum"
